apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: gitops-dev

servers: 1
agents: 2

image: rancher/k3s:v1.35.5-k3s1

ports:
  - port: 127.0.0.1:8080:80
    nodeFilters:
      - loadbalancer

options:
  k3s:
    nodeLabels:
      - label: workload=application
        nodeFilters:
          - "agent:*"
  k3d:
    wait: true
    timeout: 120s
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
