apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local-gitops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Restricted project for the local GitOps demonstration
  sourceRepos:
    - https://github.com/Owasamly/local-kubernetes-gitops.git
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  orphanedResources:
    warn: true
